n1=int(input("DIGITE O PRIMEIRO NUMERO: ")) 
n2=int(input("DIGITE O SEGUNDO NUMERO: ")) 
while n1 > n2:
    print("NUMERO INVALIDO, FAVOR DIGITAR UM NUMERO MAIOR QUE O PRIMEIRO!")
    n2=int(input("DIGITE NOVAMENTE O SEGUNDO NUMERO: ")) 